import SideBar from "@/components/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="flex overflow-y-hidden">
      <SideBar className="w-1/4" />
      <main className="flex-grow max-h-screen overflow-y-auto">{children}</main>
    </div>
  );
}
