import Provider from "@/components/Providers";
import SideBar from "@/components/Sidebar";
import TopBar from "@/components/TopBar";
import { poppins } from "@/lib/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-[#fbf9f0] ${poppins.className}`}>
        <Provider>
          {/* <TopBar /> */}
          <div className="flex">
            <SideBar className="w-1/4" />
            <main className="flex-grow">{children}</main>
          </div>
        </Provider>
      </body>
    </html>
  );
}
