import Provider from "@/components/Providers";
import "./globals.css";
import SideBar from "@/components/Sidebar";
import { inter } from "@/lib/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-[#fbf9f0] flex ${inter.classname}`}>
        <Provider>
          <SideBar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
