import SideBar from "@/components/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="flex">
      <SideBar className="w-1/4" />
      <main className="flex-grow">{children}</main>
    </div>
  );
}
